package POJOS;
// Generated Jun 23, 2018 8:08:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Educacione generated by hbm2java
 */
public class Educacione  implements java.io.Serializable {


     private int educacioneId;
     private String educacioneTipo;
     private Set postulantes = new HashSet(0);

    public Educacione() {
    }

	
    public Educacione(int educacioneId, String educacioneTipo) {
        this.educacioneId = educacioneId;
        this.educacioneTipo = educacioneTipo;
    }
    public Educacione(int educacioneId, String educacioneTipo, Set postulantes) {
       this.educacioneId = educacioneId;
       this.educacioneTipo = educacioneTipo;
       this.postulantes = postulantes;
    }
   
    public int getEducacioneId() {
        return this.educacioneId;
    }
    
    public void setEducacioneId(int educacioneId) {
        this.educacioneId = educacioneId;
    }
    public String getEducacioneTipo() {
        return this.educacioneTipo;
    }
    
    public void setEducacioneTipo(String educacioneTipo) {
        this.educacioneTipo = educacioneTipo;
    }
    public Set getPostulantes() {
        return this.postulantes;
    }
    
    public void setPostulantes(Set postulantes) {
        this.postulantes = postulantes;
    }




}


