package POJOS;
// Generated Jun 23, 2018 8:08:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int ventaId;
     private String ventaTipo;
     private Set postulantes = new HashSet(0);

    public Venta() {
    }

	
    public Venta(int ventaId, String ventaTipo) {
        this.ventaId = ventaId;
        this.ventaTipo = ventaTipo;
    }
    public Venta(int ventaId, String ventaTipo, Set postulantes) {
       this.ventaId = ventaId;
       this.ventaTipo = ventaTipo;
       this.postulantes = postulantes;
    }
   
    public int getVentaId() {
        return this.ventaId;
    }
    
    public void setVentaId(int ventaId) {
        this.ventaId = ventaId;
    }
    public String getVentaTipo() {
        return this.ventaTipo;
    }
    
    public void setVentaTipo(String ventaTipo) {
        this.ventaTipo = ventaTipo;
    }
    public Set getPostulantes() {
        return this.postulantes;
    }
    
    public void setPostulantes(Set postulantes) {
        this.postulantes = postulantes;
    }




}


